### ISSUE TITLE
Document security issue with honor_labels option

### ISSUE THREAD

**Issue by mxinden** [openshift/prom-label-proxy#2]
When Prometheus scrapes a target it applies labels to the metrics exposed by that target. To resolve the conflict between clashing label keys, Prometheus offers the [honor_labels](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config).

Let's say there is a multi-tenant Kubernetes cluster with a global Prometheus Operator and Prometheus. Prometheus is tenant aware via the prom-label-proxy. In addition let's assume that each tenant controls their Prometheus Operator ServiceMonitor.

In this scenario a malicious tenant A could set the `honor_labels` option to true and pollute the metrics of tenant B by applying the label `namespace=B` to each of their exposed metrics.

I don't see a way how the prom-label-proxy could prevent this issue. But I think documenting the concern is a good firth step. What are your thoughts?

**Comment by brancz** [comment]
Anyone who controls ingestion can do that. As you said it's not actually an issue with the label enforcing. As the readme already says and we should be clearer about this: this is not a security tool. If you plug things together that makes it part of a security story that's fine, but in terms of its responsibilities this purely performs label enforcing no more and no less.
