### ISSUE TITLE
No logs :(

### ISSUE THREAD

**Issue by angelbarrera92** [openshift/prom-label-proxy#23]
Hi!!!

I am trying to use this piece along side with a proxy that injects the ?namespace=label a a query parameter request.

I've got this setup:

AUTH_PROXY -> prom-label-proxy -> prometheus

- AUTH_PROXY: exposes basic auth and injects the namespace query parameter in the request
- prom-label-proxy: with the --label=namespace argument

I see how my AUTH_PROXY requests to prom-label-proxy but no result are returned :(
I want to debug the problem but i don't see any kind of log :(

Is this project alive?

Thanks!

**Comment by angelbarrera92** [comment]
Debugged the old way, tcpdump. Thanks

**Comment by simonpasquier** [comment]
Is there anything to be added to the project that would have helped you debug the issue more easily?

**Comment by angelbarrera92** [comment]
> Is there anything to be added to the project that would have helped you debug the issue more easily?

Maybe something like: 

before: /api/v1/query?pod=aaa
after: /api/v1/query?pod=aaa&namespace=b
--
before: /api/v1/query?pod=ccc
Not further action

Thanks!
