### ISSUE TITLE
Upstream URL is not called

### ISSUE THREAD

**Issue by dbluxo** [openshift/prom-label-proxy#25]
Hi,

I'm trying to set up the **prom-label proxy**. I have integrated the proxy into my Pod as follows:
```
- name: prom-label-proxy
  image: quay.io/coreos/prom-label-proxy:v0.1.0
  args:
  - --insecure-listen-address=127.0.0.1:9095
  - --upstream=http://prometheus-http:80/
  - --label=namespace
```
The proxy starts with the following log message:
`2020/03/23 14:49:11 Listening insecurely on 127.0.0.1:9095`

For simplicity I'm executing a curl in the same Pod:
```
curl -v "http://127.0.0.1:9095/api/v1/query?query=container_cpu_usage_seconds_total\&namespace=labor"

* About to connect() to 127.0.0.1 port 9095 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9095 (#0)
> GET /api/v1/query?query=container_cpu_usage_seconds_total\&namespace=labor HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:9095
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Mon, 23 Mar 2020 15:26:26 GMT
< Content-Length: 0
<
* Connection #0 to host 127.0.0.1 left intact

```
No matter what I do, I never get Prometheus metrics back. I also have the feeling that the upstream address is never called and the status code remains always at 200. I don't see any requests to Prometheus in tcpdump either.

Can you please help me?

**Comment by HenriAW** [comment]
Hi @dbluxo, I'm facing the same issue. Did you manage to resolve this?

**Comment by dbluxo** [comment]
My mistake was that the curl address was given with quotation marks:

`curl -v "http://127.0.0.1:9095/api/v1/query?query=container_cpu_usage_seconds_total\&namespace=labor"` :x:

should be:

`curl -v http://127.0.0.1:9095/api/v1/query?query=container_cpu_usage_seconds_total\&namespace=labor` :white_check_mark:
